final class AyanamshaValue {
  const AyanamshaValue({
    required this.julianDayTt,
    required this.degrees,
    required this.sourceId,
    required this.sourceVersion,
    required this.dataSha256,
  });

  final double julianDayTt;
  final double degrees;
  final String sourceId;
  final String sourceVersion;
  final String dataSha256;
}

abstract interface class AyanamshaProvider {
  String get sourceId;
  String get sourceVersion;
  String get dataSha256;
  double get coverageStartJulianDayTt;
  double get coverageEndJulianDayTt;

  AyanamshaValue atJulianDayTt(double julianDayTt);
}

final class AyanamshaSample {
  const AyanamshaSample({required this.julianDayTt, required this.degrees});

  final double julianDayTt;
  final double degrees;
}

/// Strict offline provider for an independently sourced ayanamsha table.
///
/// The provider deliberately does not invent an astronomical formula. A release
/// can bundle a validated Lahiri/Chitrapaksha table (or a table generated by a
/// separately verified implementation), record its provenance/checksum, and
/// interpolate only inside the covered interval. Extrapolation is forbidden.
final class TabulatedAyanamshaProvider implements AyanamshaProvider {
  TabulatedAyanamshaProvider({
    required this.sourceId,
    required this.sourceVersion,
    required this.dataSha256,
    required List<AyanamshaSample> samples,
  }) : _samples = List<AyanamshaSample>.unmodifiable(samples) {
    _validateProvenance(sourceId, 'sourceId');
    _validateProvenance(sourceVersion, 'sourceVersion');
    if (!RegExp(r'^[0-9a-fA-F]{64}$').hasMatch(dataSha256)) {
      throw ArgumentError.value(dataSha256, 'dataSha256', 'Expected a 64-character SHA-256 hex digest.');
    }
    if (_samples.length < 2) {
      throw ArgumentError.value(samples.length, 'samples', 'At least two samples are required.');
    }
    for (var index = 0; index < _samples.length; index += 1) {
      final sample = _samples[index];
      if (!sample.julianDayTt.isFinite) {
        throw ArgumentError.value(sample.julianDayTt, 'samples[$index].julianDayTt', 'Value must be finite.');
      }
      if (!sample.degrees.isFinite || sample.degrees < 0 || sample.degrees >= 360) {
        throw RangeError.range(sample.degrees, 0, 360, 'samples[$index].degrees', 'Expected 0 <= degrees < 360.');
      }
      if (index > 0 && sample.julianDayTt <= _samples[index - 1].julianDayTt) {
        throw ArgumentError('Ayanamsha samples must have strictly increasing TT Julian days.');
      }
    }
  }

  @override
  final String sourceId;

  @override
  final String sourceVersion;

  @override
  final String dataSha256;

  final List<AyanamshaSample> _samples;

  @override
  double get coverageStartJulianDayTt => _samples.first.julianDayTt;

  @override
  double get coverageEndJulianDayTt => _samples.last.julianDayTt;

  @override
  AyanamshaValue atJulianDayTt(double julianDayTt) {
    if (!julianDayTt.isFinite) {
      throw ArgumentError.value(julianDayTt, 'julianDayTt', 'Value must be finite.');
    }
    if (julianDayTt < coverageStartJulianDayTt || julianDayTt > coverageEndJulianDayTt) {
      throw RangeError.range(
        julianDayTt,
        coverageStartJulianDayTt,
        coverageEndJulianDayTt,
        'julianDayTt',
        'Ayanamsha extrapolation is forbidden.',
      );
    }

    var low = 0;
    var high = _samples.length - 1;
    while (low <= high) {
      final mid = low + ((high - low) >> 1);
      final sample = _samples[mid];
      if (sample.julianDayTt == julianDayTt) {
        return _result(julianDayTt, sample.degrees);
      }
      if (sample.julianDayTt < julianDayTt) {
        low = mid + 1;
      } else {
        high = mid - 1;
      }
    }

    final right = _samples[low];
    final left = _samples[low - 1];
    final fraction = (julianDayTt - left.julianDayTt) / (right.julianDayTt - left.julianDayTt);
    final degrees = left.degrees + (right.degrees - left.degrees) * fraction;
    return _result(julianDayTt, degrees);
  }

  AyanamshaValue _result(double julianDayTt, double degrees) => AyanamshaValue(
        julianDayTt: julianDayTt,
        degrees: degrees,
        sourceId: sourceId,
        sourceVersion: sourceVersion,
        dataSha256: dataSha256.toLowerCase(),
      );

  static void _validateProvenance(String value, String name) {
    if (value.trim().isEmpty) {
      throw ArgumentError.value(value, name, 'Provenance must not be empty.');
    }
  }
}
