import 'package:flutter_test/flutter_test.dart';
import 'package:ruh_code/src/calculation_core/ephemeris/ephemeris.dart';
import 'package:ruh_code/src/calculation_core/vedic/vedic_engine.dart';
import 'package:ruh_code/src/calculation_core/vedic/vedic_varga.dart';

VedicCalculationSnapshot _snapshot(double longitude)=>VedicCalculationSnapshot(jdTt:2451545.0,ephemerisSourceId:'fixture',ephemerisDataVersion:'v1',ayanamshaId:'lahiri-chitrapaksha',ayanamshaDataVersion:'fixture-v1',ayanamshaDegrees:24,placements:[VedicPlacement(body:AstroBody.sun,siderealLongitudeDegrees:longitude,longitudeSpeedDegreesPerDay:1)]);

void main(){
  test('RC-0092 Navamsa D9 uses movable/fixed/dual start rules',(){expect(VedicVargaBuilder.navamsaD9(_snapshot(1)).placements.single.vargaRashiIndex,0);expect(VedicVargaBuilder.navamsaD9(_snapshot(31)).placements.single.vargaRashiIndex,9);expect(VedicVargaBuilder.navamsaD9(_snapshot(61)).placements.single.vargaRashiIndex,6);});
  test('RC-0093 Hora D2 odd/even order',(){expect(VedicVargaBuilder.horaD2(_snapshot(5)).placements.single.vargaRashiIndex,4);expect(VedicVargaBuilder.horaD2(_snapshot(20)).placements.single.vargaRashiIndex,3);expect(VedicVargaBuilder.horaD2(_snapshot(35)).placements.single.vargaRashiIndex,3);expect(VedicVargaBuilder.horaD2(_snapshot(50)).placements.single.vargaRashiIndex,4);});
  test('RC-0094 Drekkana D3 maps thirds to 1st 5th 9th signs',(){expect(VedicVargaBuilder.drekkanaD3(_snapshot(5)).placements.single.vargaRashiIndex,0);expect(VedicVargaBuilder.drekkanaD3(_snapshot(15)).placements.single.vargaRashiIndex,4);expect(VedicVargaBuilder.drekkanaD3(_snapshot(25)).placements.single.vargaRashiIndex,8);});
  test('RC-0095 Chaturthamsa D4 maps quarters to 1st 4th 7th 10th signs',(){expect(VedicVargaBuilder.chaturthamsaD4(_snapshot(1)).placements.single.vargaRashiIndex,0);expect(VedicVargaBuilder.chaturthamsaD4(_snapshot(8)).placements.single.vargaRashiIndex,3);expect(VedicVargaBuilder.chaturthamsaD4(_snapshot(16)).placements.single.vargaRashiIndex,6);expect(VedicVargaBuilder.chaturthamsaD4(_snapshot(24)).placements.single.vargaRashiIndex,9);});
  test('RC-0096 Saptamsa D7 odd starts same even starts seventh',(){expect(VedicVargaBuilder.saptamsaD7(_snapshot(1)).placements.single.vargaRashiIndex,0);expect(VedicVargaBuilder.saptamsaD7(_snapshot(31)).placements.single.vargaRashiIndex,7);});
  test('RC-0096 Saptamsa D7 advances zodiacally across seven parts',(){final p=VedicVargaBuilder.saptamsaD7(_snapshot(25.8)).placements.single;expect(p.divisionIndex,6);expect(p.vargaRashiIndex,6);});
  test('RC-0097 Dasamsa D10 odd starts same even starts ninth',(){expect(VedicVargaBuilder.dasamsaD10(_snapshot(1)).placements.single.vargaRashiIndex,0);expect(VedicVargaBuilder.dasamsaD10(_snapshot(31)).placements.single.vargaRashiIndex,9);});
  test('RC-0097 Dasamsa D10 advances every three degrees',(){final p=VedicVargaBuilder.dasamsaD10(_snapshot(5)).placements.single;expect(p.divisionIndex,1);expect(p.vargaRashiIndex,1);});
  test('RC-0098 Dwadasamsa D12 starts from natal sign and advances',(){expect(VedicVargaBuilder.dwadasamsaD12(_snapshot(1)).placements.single.vargaRashiIndex,0);expect(VedicVargaBuilder.dwadasamsaD12(_snapshot(3)).placements.single.vargaRashiIndex,1);expect(VedicVargaBuilder.dwadasamsaD12(_snapshot(59.9)).placements.single.vargaRashiIndex,0);});
  test('RC-0099 Shodasamsa D16 uses movable Aries fixed Leo dual Sagittarius starts',(){expect(VedicVargaBuilder.shodasamsaD16(_snapshot(1)).placements.single.vargaRashiIndex,0);expect(VedicVargaBuilder.shodasamsaD16(_snapshot(31)).placements.single.vargaRashiIndex,4);expect(VedicVargaBuilder.shodasamsaD16(_snapshot(61)).placements.single.vargaRashiIndex,8);});
  test('RC-0099 Shodasamsa D16 advances every 1.875 degrees',(){final p=VedicVargaBuilder.shodasamsaD16(_snapshot(3.8)).placements.single;expect(p.divisionIndex,2);expect(p.vargaRashiIndex,2);});
  test('RC-0100 Vimshamsa D20 uses movable Aries fixed Sagittarius dual Leo starts',(){expect(VedicVargaBuilder.vimshamsaD20(_snapshot(1)).placements.single.vargaRashiIndex,0);expect(VedicVargaBuilder.vimshamsaD20(_snapshot(31)).placements.single.vargaRashiIndex,8);expect(VedicVargaBuilder.vimshamsaD20(_snapshot(61)).placements.single.vargaRashiIndex,4);});
  test('RC-0100 Vimshamsa D20 advances every 1.5 degrees',(){final p=VedicVargaBuilder.vimshamsaD20(_snapshot(3.1)).placements.single;expect(p.divisionIndex,2);expect(p.vargaRashiIndex,2);});
  test('RC-0101 Chaturvimshamsa D24 starts Leo for odd signs and Cancer for even signs',(){expect(VedicVargaBuilder.chaturvimshamsaD24(_snapshot(1)).placements.single.vargaRashiIndex,4);expect(VedicVargaBuilder.chaturvimshamsaD24(_snapshot(31)).placements.single.vargaRashiIndex,3);});
  test('RC-0101 Chaturvimshamsa D24 advances every 1.25 degrees',(){final p=VedicVargaBuilder.chaturvimshamsaD24(_snapshot(3.8)).placements.single;expect(p.divisionIndex,3);expect(p.vargaRashiIndex,7);});
  test('RC-0102 Trimshamsa D30 uses classical unequal odd-sign spans',(){expect(VedicVargaBuilder.trimshamsaD30(_snapshot(4.999)).placements.single.vargaRashiIndex,0);expect(VedicVargaBuilder.trimshamsaD30(_snapshot(5)).placements.single.vargaRashiIndex,10);expect(VedicVargaBuilder.trimshamsaD30(_snapshot(10)).placements.single.vargaRashiIndex,8);expect(VedicVargaBuilder.trimshamsaD30(_snapshot(18)).placements.single.vargaRashiIndex,2);expect(VedicVargaBuilder.trimshamsaD30(_snapshot(25)).placements.single.vargaRashiIndex,6);});
  test('RC-0102 Trimshamsa D30 reverses ruler signs for even Rashi',(){expect(VedicVargaBuilder.trimshamsaD30(_snapshot(34.999)).placements.single.vargaRashiIndex,1);expect(VedicVargaBuilder.trimshamsaD30(_snapshot(35)).placements.single.vargaRashiIndex,5);expect(VedicVargaBuilder.trimshamsaD30(_snapshot(42)).placements.single.vargaRashiIndex,11);expect(VedicVargaBuilder.trimshamsaD30(_snapshot(50)).placements.single.vargaRashiIndex,9);expect(VedicVargaBuilder.trimshamsaD30(_snapshot(55)).placements.single.vargaRashiIndex,7);});
  test('RC-0102 Trimshamsa D30 preserves unequal-segment position',(){final p=VedicVargaBuilder.trimshamsaD30(_snapshot(14)).placements.single;expect(p.division,30);expect(p.divisionIndex,2);expect(p.degreesWithinVargaRashi,closeTo(15,1e-9));});
  test('RC-0103 Shashtiamsa D60 advances every half degree from natal Rashi by default',(){expect(VedicVargaBuilder.shashtiamsaD60(_snapshot(30.1)).placements.single.vargaRashiIndex,1);expect(VedicVargaBuilder.shashtiamsaD60(_snapshot(30.5)).placements.single.vargaRashiIndex,2);expect(VedicVargaBuilder.shashtiamsaD60(_snapshot(35.5)).placements.single.vargaRashiIndex,0);});
  test('RC-0103 Shashtiamsa D60 exposes sign-independent classical-reading fork',(){final p=VedicVargaBuilder.shashtiamsaD60(_snapshot(30.5),convention:VedicShashtiamsaSignConvention.signIndependent).placements.single;expect(p.divisionIndex,1);expect(p.vargaRashiIndex,1);});
  test('RC-0104 systematic equal Varga definition is validated and deterministic',(){final d=VedicEqualVargaDefinition(id:'fixture-d5',division:5,startRashiByNatalRashi:List<int>.generate(12,(i)=>i));final p=VedicVargaBuilder.buildSystematicEqualVarga(_snapshot(37),d).placements.single;expect(p.division,5);expect(p.divisionIndex,1);expect(p.vargaRashiIndex,2);expect(()=>VedicEqualVargaDefinition(id:'bad',division:5,startRashiByNatalRashi:const[0]),throwsArgumentError);});
  test('RC-0092-RC-0104 fail closed on invalid provenance',(){final invalid=VedicCalculationSnapshot(jdTt:2451545,ephemerisSourceId:'',ephemerisDataVersion:'v1',ayanamshaId:'lahiri-chitrapaksha',ayanamshaDataVersion:'fixture-v1',ayanamshaDegrees:24,placements:const[VedicPlacement(body:AstroBody.sun,siderealLongitudeDegrees:10,longitudeSpeedDegreesPerDay:1)]);expect(()=>VedicVargaBuilder.navamsaD9(invalid),throwsStateError);expect(()=>VedicVargaBuilder.saptamsaD7(invalid),throwsStateError);expect(()=>VedicVargaBuilder.shodasamsaD16(invalid),throwsStateError);expect(()=>VedicVargaBuilder.vimshamsaD20(invalid),throwsStateError);expect(()=>VedicVargaBuilder.chaturvimshamsaD24(invalid),throwsStateError);expect(()=>VedicVargaBuilder.trimshamsaD30(invalid),throwsStateError);expect(()=>VedicVargaBuilder.shashtiamsaD60(invalid),throwsStateError);});
}
