import 'package:flutter_test/flutter_test.dart';
import 'package:ruh_code/src/calculation_core/ephemeris/ephemeris.dart';
import 'package:ruh_code/src/calculation_core/vedic/vedic_engine.dart';
import 'package:ruh_code/src/calculation_core/vedic/vedic_varga.dart';

VedicCalculationSnapshot _snapshot(double longitude)=>VedicCalculationSnapshot(jdTt:2451545.0,ephemerisSourceId:'fixture',ephemerisDataVersion:'v1',ayanamshaId:'lahiri-chitrapaksha',ayanamshaDataVersion:'fixture-v1',ayanamshaDegrees:24,placements:[VedicPlacement(body:AstroBody.sun,siderealLongitudeDegrees:longitude,longitudeSpeedDegreesPerDay:1)]);

void main(){
  test('RC-0092 Navamsa D9 uses movable/fixed/dual start rules',(){expect(VedicVargaBuilder.navamsaD9(_snapshot(1)).placements.single.vargaRashiIndex,0);expect(VedicVargaBuilder.navamsaD9(_snapshot(31)).placements.single.vargaRashiIndex,9);expect(VedicVargaBuilder.navamsaD9(_snapshot(61)).placements.single.vargaRashiIndex,6);});
  test('RC-0093 Hora D2 odd/even order',(){expect(VedicVargaBuilder.horaD2(_snapshot(5)).placements.single.vargaRashiIndex,4);expect(VedicVargaBuilder.horaD2(_snapshot(20)).placements.single.vargaRashiIndex,3);expect(VedicVargaBuilder.horaD2(_snapshot(35)).placements.single.vargaRashiIndex,3);expect(VedicVargaBuilder.horaD2(_snapshot(50)).placements.single.vargaRashiIndex,4);});
  test('RC-0094 Drekkana D3 maps thirds to 1st 5th 9th signs',(){expect(VedicVargaBuilder.drekkanaD3(_snapshot(5)).placements.single.vargaRashiIndex,0);expect(VedicVargaBuilder.drekkanaD3(_snapshot(15)).placements.single.vargaRashiIndex,4);expect(VedicVargaBuilder.drekkanaD3(_snapshot(25)).placements.single.vargaRashiIndex,8);});
  test('RC-0095 Chaturthamsa D4 maps quarters to 1st 4th 7th 10th signs',(){expect(VedicVargaBuilder.chaturthamsaD4(_snapshot(1)).placements.single.vargaRashiIndex,0);expect(VedicVargaBuilder.chaturthamsaD4(_snapshot(8)).placements.single.vargaRashiIndex,3);expect(VedicVargaBuilder.chaturthamsaD4(_snapshot(16)).placements.single.vargaRashiIndex,6);expect(VedicVargaBuilder.chaturthamsaD4(_snapshot(24)).placements.single.vargaRashiIndex,9);});
  test('RC-0096 Saptamsa D7 odd starts same even starts seventh',(){expect(VedicVargaBuilder.saptamsaD7(_snapshot(1)).placements.single.vargaRashiIndex,0);expect(VedicVargaBuilder.saptamsaD7(_snapshot(31)).placements.single.vargaRashiIndex,7);});
  test('RC-0096 Saptamsa D7 advances zodiacally across seven parts',(){final p=VedicVargaBuilder.saptamsaD7(_snapshot(25.8)).placements.single;expect(p.divisionIndex,6);expect(p.vargaRashiIndex,6);});
  test('RC-0097 Dasamsa D10 odd starts same even starts ninth',(){expect(VedicVargaBuilder.dasamsaD10(_snapshot(1)).placements.single.vargaRashiIndex,0);expect(VedicVargaBuilder.dasamsaD10(_snapshot(31)).placements.single.vargaRashiIndex,9);});
  test('RC-0097 Dasamsa D10 advances every three degrees',(){final p=VedicVargaBuilder.dasamsaD10(_snapshot(5)).placements.single;expect(p.divisionIndex,1);expect(p.vargaRashiIndex,1);});
  test('RC-0098 Dwadasamsa D12 starts from natal sign and advances',(){expect(VedicVargaBuilder.dwadasamsaD12(_snapshot(1)).placements.single.vargaRashiIndex,0);expect(VedicVargaBuilder.dwadasamsaD12(_snapshot(3)).placements.single.vargaRashiIndex,1);expect(VedicVargaBuilder.dwadasamsaD12(_snapshot(59.9)).placements.single.vargaRashiIndex,0);});
  test('RC-0092-RC-0098 fail closed on invalid provenance',(){final invalid=VedicCalculationSnapshot(jdTt:2451545,ephemerisSourceId:'',ephemerisDataVersion:'v1',ayanamshaId:'lahiri-chitrapaksha',ayanamshaDataVersion:'fixture-v1',ayanamshaDegrees:24,placements:const[VedicPlacement(body:AstroBody.sun,siderealLongitudeDegrees:10,longitudeSpeedDegreesPerDay:1)]);expect(()=>VedicVargaBuilder.navamsaD9(invalid),throwsStateError);expect(()=>VedicVargaBuilder.saptamsaD7(invalid),throwsStateError);expect(()=>VedicVargaBuilder.dasamsaD10(invalid),throwsStateError);expect(()=>VedicVargaBuilder.dwadasamsaD12(invalid),throwsStateError);});
}
